app/ext/db/models.py
from app.ext.db import db


class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String)
    password = db.Column(db.String)

    def __repr__(self):
        return f'User(email={self.email})'

app/app.py
from flask import Flask
from app.ext import conf


def create_app():
    """Factory that will create our app"""
    app = Flask(__name__)
    conf.init_app(app)

    return app

app/ext/admin/__init__.py
from flask_admin import Admin


admin = Admin()


def init_app(app):
    admin.name = "Login Page"
    admin.template_mode = "bootstrap2"

    admin.init_app(app)

app/ext/cli/__init__.py
import click
from app.ext.db import db
from app.ext.db import models


def init_app(app):

    @app.cli.command()
    def create_db():
        """Este comando inicializa o db"""
        db.create_all()

    @app.cli.command()
    @click.option("--email", "-e")
    @click.option("--password", "-p")
    def add_user(email, password):
        """Este comando adiciona novos usuarios através do shell"""
        user = models.User(
            email=email,
            password=password
        )

        db.session.add(user)
        db.session.commit()

app/ext/conf/__init__.py
from dynaconf import FlaskDynaconf


def init_app(app):
    FlaskDynaconf(app)
    app.config.load_extensions("INSTALLED_APPS")

app/ext/db/__init__.py
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


def init_app(app):
    db.init_app(app)

app/ext/site/__init__.py
from app.ext.site.views import bp


def init_app(app):
    app.register_blueprint(bp)

app/ext/site/views.py
from flask import Blueprint, render_template, request, flash
from app.ext.auth.controller import create_user, check_user_existance


bp = Blueprint("site", __name__)


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/register', methods=["GET", "POST"])
def register():
    msg = None
    if request.method == "POST":
        email = request.form['email']
        password = request.form['password']
        
        check_user = check_user_existance(email)
       
        if check_user:
            msg = "Email já cadastrado"
        else:
            create_user(email, password)
            msg = 'Usuário cadastrado com sucesso'

            
    return render_template('register.html', msg=msg)

app/templates/index.html
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <title>Index</title>
  </head>
  <body>
    <header>Page Header</header>
    <main>
      <h1>Hello Page</h1>
    </main>
    <footer>Page footer</footer>
  </body>
</html>

app/templates/register.html
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="static/style.css">
    <meta charset="UTF-8"/>
    <title>Document</title>

  </head>
  <body>
    <form action="{{ url_for('site.register')  }}" method="post">
    <div>
        <label for="email">Email:</label>
        <input  type="email" name="email"/>
    </div>
    <div>
        <label for="password">Password:</label>
        <input type="password" name="password" />
    </div>
    <div class="button">
      <button type="submit">Cadastre-se</button>
    </div>

</form>
  </body>
</html>